// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hello_cpp
XPtr<std::string> hello_cpp();
RcppExport SEXP _cdfdistances_hello_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(hello_cpp());
    return rcpp_result_gen;
END_RCPP
}
// evaluate
String evaluate(XPtr<std::string> x);
RcppExport SEXP _cdfdistances_evaluate(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< XPtr<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cdfdistances_hello_cpp", (DL_FUNC) &_cdfdistances_hello_cpp, 0},
    {"_cdfdistances_evaluate", (DL_FUNC) &_cdfdistances_evaluate, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cdfdistances(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
