# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdf_from_obs <- function(obs) {
    .Call(`_cdfdistances_cdf_from_obs`, obs)
}

cdf_from_timing <- function(t, obs) {
    .Call(`_cdfdistances_cdf_from_timing`, t, obs)
}

eval_cdf <- function(cdf, x) {
    .Call(`_cdfdistances_eval_cdf`, cdf, x)
}

wasserstein <- function(cdf1, cdf2) {
    .Call(`_cdfdistances_wasserstein`, cdf1, cdf2)
}

